apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-notifications-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build-notifications
  template:
    metadata:
      labels:
        app: build-notifications
    spec:
      containers:
        - name: build-notifications
          image: a71816/micro-twitter-build-notifications
          env:
            - name: RABBITMQ_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: rabbitmq-root-username
            - name: RABBITMQ_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: rabbitmq-root-password
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: build-notifications-configmap
                  key: rabbitmq_host
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_ROOT_USERNAME):$(RABBITMQ_ROOT_PASSWORD)@$(RABBITMQ_HOST)"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: build-notifications-configmap
                  key: redis_host
            - name: REDIS_URL
              value: "redis://$(REDIS_HOST)"
