apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-notifications-redis-depl
  labels:
    app: build-notifications-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: build-notifications-redis
  template:
    metadata:
      labels:
        app: build-notifications-redis
    spec:
      containers:
        - name: build-notifications-redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: build-notifications-redis-srv
spec:
  selector:
    app: build-notifications-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379
