apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-redis-depl
  labels:
    app: notify-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notify-redis
  template:
    metadata:
      labels:
        app: notify-redis
    spec:
      containers:
        - name: notify-redis
          image: redis
          ports:
            - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: notify-redis-srv
spec:
  selector:
    app: notify-redis
  ports:
    - name: db
      protocol: TCP
      port: 6379
      targetPort: 6379
