apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: twitter-ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
    - host: twitter.dev
      http:
        paths:
          - path: /api/users/?(.*)
            pathType: Prefix
            backend:
              service:
                name: users-srv
                port:
                  number: 3000
          - path: /api/followships/?(.*)
            pathType: Prefix
            backend:
              service:
                name: followships-srv
                port:
                  number: 3000
          - path: /api/subscribeships/?(.*)
            pathType: Prefix
            backend:
              service:
                name: subscribeships-srv
                port:
                  number: 3000
          - path: /api/tweets/?(.*)
            pathType: Prefix
            backend:
              service:
                name: tweets-srv
                port:
                  number: 3000
          - path: /api/likes/?(.*)
            pathType: Prefix
            backend:
              service:
                name: tweets-srv
                port:
                  number: 3000
          - path: /api/replies/?(.*)
            pathType: Prefix
            backend:
              service:
                name: tweets-srv
                port:
                  number: 3000
          - path: /api/notify/?(.*)
            pathType: Prefix
            backend:
              service:
                name: notify-srv
                port:
                  number: 3000
