apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscribeships-mysql-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscribeships-mysql
  template:
    metadata:
      labels:
        app: subscribeships-mysql
    spec:
      containers:
        - name: subscribeships-mysql
          image: mysql
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: subscribeships-configmap
                  key: mysql_database
---
apiVersion: v1
kind: Service
metadata:
  name: subscribeships-mysql-srv
spec:
  selector:
    app: subscribeships-mysql
  ports:
    - name: db
      protocol: TCP
      port: 3306
      targetPort: 3306
