name: build-notifications-test

on:
  pull_request:
    paths:
      - 'build-notification/**'
  
jobs:
  build_notification_test:
    runs-on: ubuntu-latest
    
    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672
      redis:
        image: redis
        ports:
          - 6379
          
    steps:
      - uses: actions/checkout@v2
      - name: run test
        run: |
          cd build-notification
          npm install
          npm run test:ci
        env:
          RABBITMQ_URL: "amqp://127.0.0.1:${{ job.services.rabbitmq.ports['5672'] }}"
          JWT_KEY: test
          REDIS_URL: "redis://127.0.0.1:${{ job.services.redis.ports['6379'] }}"
