name: followships-tests

on:
  pull_request:
    paths:
      - 'followships/**'
      
      
jobs:
  followships_tests:
    runs-on: ubuntu-latest
    
    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test-micro-twitter-followship
        ports:
          - 3306
        options: >-
          --name=mysql
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          
    steps:
      - uses: actions/checkout@v2
      - name: run test
        run: |
          cd followships
          npm install
          npm run test:ci
        env:
          MYSQL_URL: "mysql://root:${{ job.services.mysql.env.MYSQL_ROOT_PASSWORD }}@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/${{ job.services.mysql.env.MYSQL_DATABASE }}"
          RABBITMQ_URL: "amqp://127.0.0.1:${{ job.services.rabbitmq.ports['5672'] }}"
          
