name: tweets-test

on:
  pull_request

jobs:
  tweets_test:
    runs-on: ubuntu-latest
    env:
      MONGO_URL: mongodb://root:password@localhost:27017/tweets
      JWT_KEY: test
      RABBITMQ_URL: amqp://localhost:5672
    steps:
      - run: cd users && npm install && npm run test:ci
