name: users-tests

on:
  pull_request:
    paths:
      - 'users/**'

jobs:
  users_tests:
    runs-on: ubuntu-latest
    
    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672
      
    steps:
       - uses: actions/checkout@v2
       - name: run test
         run: |
          cd users
          npm install
          npm run test:ci
         env:
           RABBITMQ_URL: ${{ job.services.rabbitmq.ports['5672'] }}
