name: users-tests

on:
  pull_request

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - env:
          MONGO_URL: mongodb://users-mongo-srv:27017/users
          RABBITMQ_URL: amqp://localhost:5672
          JWT_KEY: test
        run: cd users && npm install && npm run test:ci
