name: users-tests

on:
  pull_request:
    paths:
      - 'users/**'

jobs:
  users_tests:
    runs-on: ubuntu-latest
    env:
      RABBITMQ_URL: amqp://localhost:5672
    steps:
       - uses: actions/checkout@v2
       - name: run rabbitmq
         run: docker run --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.11-management
       - name: run test
         run: |
          cd users
          npm install
          npm run test:ci
