name: users-tests

on:
  pull_request:
    paths:
      - 'users/**'

jobs:
  users_tests:
    runs-on: ubuntu-latest
    env:
      RABBITMQ_URL: amqp://localhost:1883
      
    steps:
       - uses: actions/checkout@v2
       - name: run rabbitmq
         uses: namoshek/rabbitmq-github-action@v1
         with:
          container-name: 'mqtt'
       - name: run test
         run: |
          cd users
          npm install
          npm run test:ci
