name: users-tests

on:
  pull_request

jobs:
  users_tests:
    runs-on: ubuntu-latest
    env:
      MONGO_URL: mongodb://users-mongo-srv:27017/users
      RABBITMQ_URL: amqp://localhost:5672
      JWT_KEY: test    
    steps:
       - uses: actions/checkout@v2
       - run: cd users && npm install && npm run test:ci
