apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweets
  template:
    metadata:
      labels:
        app: tweets
    spec:
      containers:
        - name: micro-twitter-tweets
          image: a71816/micro-twitter-tweets
          ports:
            - containerPort: 3000
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: jwt-key
            - name: RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: tweets-configmap
                  key: rabbitmq_host
            - name: RABBITMQ_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: rabbitmq-root-username
            - name: RABBITMQ_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: rabbitmq-root-password
            - name: RABBITMQ_URL
              value: "amqp://$(RABBITMQ_ROOT_USERNAME):$(RABBITMQ_ROOT_PASSWORD)@$(RABBITMQ_HOST)"
            - name: MONGO_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mongo-root-username
            - name: MONGO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mongo-root-password
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: tweets-configmap
                  key: mongo_host
            - name: MONGO_URL
              value: "mongodb://$(MONGO_ROOT_USERNAME):$(MONGO_ROOT_PASSWORD)@$(MONGO_HOST)"
      # volumes:
      #   - name: tweets-config
---
apiVersion: v1
kind: Service
metadata:
  name: tweets-srv
spec:
  selector:
    app: tweets
  ports:
    - name: tweets
      protocol: TCP
      port: 3000
      targetPort: 3000
