apiVersion: apps/v1
kind: Deployment
metadata:
  name: tweets-mongo-depl
  labels:
    app: tweets-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tweets-mongo
  template:
    metadata:
      labels:
        app: tweets-mongo
    spec:
      containers:
        - name: tweets-mongo
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-secret
                  key: mongo-root-password
---
apiVersion: v1
kind: Service
metadata:
  name: tweets-mongo-srv
spec:
  selector:
    app: tweets-mongo
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
